### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by alexedwards** [tomasen/realip#4]
I couldn't see any mention of what license the package is made available under. Could you add a LICENSE file (https://help.github.com/articles/adding-a-license-to-a-repository/)?

**Comment by vinceprignano** [comment]
@tomasen is it possible to add a LICENSE?

**Comment by shabbyrobe** [comment]
Unfortunately I'm being forced to remove realip from my company's code because of this issue. It would help me tremendously if this could be resolved with a permissive license. BSD or MIT is my personal preference, but of course others may have a different view!

**Comment by tomasen** [comment]
done

**Comment by shabbyrobe** [comment]
Amazing, thank you very much!

**Comment by alexedwards** [comment]
Thank you!
